### ISSUE TITLE
handle broken symlinks

### ISSUE THREAD

**Issue by pavelsr** [fooltruth/nginxctl#5]
If I have a broken symlink in ```/etc/nginx/sites-enabled``` nginxctl will show an error like:
```IOError: [Errno 2] No such file or directory: '/etc/nginx/sites-enabled/ali-tinkoff'```

We can avoid it by checking via commands:

```find . -xtype l```

or

```find . -type l -! -exec test -e {} \; -print```

http://unix.stackexchange.com/questions/34248/how-can-i-find-broken-symlinks

**Comment by fooltruth** [comment]
Thanks for reporting this. This issue is fixed with new released version. Ref: https://github.com/fooltruth/nginxctl/pull/6
